# Generated by Django 3.2.9 on 2021-12-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('building', models.CharField(max_length=128, verbose_name='Room')),
                ('room_number', models.CharField(max_length=32, verbose_name='Room Number/ Name')),
                ('capacity', models.IntegerField(verbose_name='Room Number')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('lab', 'Lab')], max_length=10, verbose_name='Type')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='faculty.department', verbose_name='Department')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
