# Generated by Django 3.2.9 on 2021-12-01 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211201_0931'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('day_of_week', models.CharField(max_length=14, verbose_name='Day of the Week')),
                ('start_effect_date', models.DateField(verbose_name='Start Effect Date')),
                ('end_effect_date', models.DateField(verbose_name='End Effect Date')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='faculty.department', verbose_name='Department'),
        ),
    ]
