# Generated by Django 3.2.9 on 2021-12-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20211201_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
    ]
