# Generated by Django 3.2.9 on 2022-02-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0003_auto_20220116_2000'),
        ('routine', '0007_auto_20220105_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=16, verbose_name='Day of week')),
                ('course_dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='semester.coursedistribution', verbose_name='Course Distribution')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='routine.slotdetail', verbose_name='Slot')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('slot', 'course_dist', 'day_of_week'), name='unique_routine'),
        ),
    ]
