# Generated by Django 3.2.9 on 2022-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0008_auto_20220206_1036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routine',
            name='unique_routine',
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('slot', 'day_of_week'), name='unique_routine'),
        ),
    ]
