# Generated by Django 3.2.9 on 2022-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_auto_20220206_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmaster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'inactive')], default='active', max_length=16, verbose_name='Status'),
        ),
    ]
