# Generated by Django 3.2.9 on 2022-02-07 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0010_alter_slotmaster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='routine.room', verbose_name='Room'),
        ),
    ]
