# Generated by Django 3.2.9 on 2022-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0011_routine_room'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routine',
            name='unique_routine',
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('slot', 'room', 'day_of_week'), name='unique_routine'),
        ),
    ]
