# Generated by Django 3.2.9 on 2022-02-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0012_auto_20220207_0948'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routine',
            name='unique_routine',
        ),
    ]
