# Generated by Django 3.2.9 on 2022-03-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0012_alter_distributedsectiondetail_distribution'),
        ('routine', '0013_remove_routine_unique_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='dummy_department',
            field=models.CharField(max_length=128, null=True, verbose_name='Dummy Department'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='course_dist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='semester.coursedistribution', verbose_name='Course Distribution'),
        ),
    ]
