# Generated by Django 3.2.9 on 2023-02-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_auto_20230226_2142'),
        ('routine', '0014_auto_20220303_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='routine.building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='faculty.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='routine.room', verbose_name='Room'),
        ),
    ]
