# Generated by Django 3.2.9 on 2022-01-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('faculty', '0005_auto_20220113_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('semester_code', models.CharField(max_length=128, verbose_name='Semester Code')),
                ('name', models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('spring', 'Spring')], max_length=8, verbose_name='Name')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='student.batch', verbose_name='Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='faculty.course', verbose_name='Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='semester.semester', verbose_name='Semester')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='semester.courseoffered', verbose_name='Course Offered')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributions', to='student.section', verbose_name='Section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributions', to='faculty.teacher', verbose_name='Teacher')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
