# Generated by Django 3.2.9 on 2022-01-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedistribution',
            options={'verbose_name': 'Course Distribution', 'verbose_name_plural': 'Course Distributions'},
        ),
        migrations.AlterModelOptions(
            name='courseoffered',
            options={'verbose_name': 'Course Offered', 'verbose_name_plural': 'Courses Offered'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
    ]
