# Generated by Django 3.2.9 on 2022-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_auto_20220113_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_code',
        ),
        migrations.AddField(
            model_name='semester',
            name='end_effect_date',
            field=models.DateField(null=True, verbose_name='End Effect Date'),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_effect_date',
            field=models.DateField(null=True, verbose_name='Start Effect Date'),
        ),
    ]
