# Generated by Django 3.2.9 on 2022-02-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0003_auto_20220116_2000'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursedistribution',
            constraint=models.UniqueConstraint(fields=('offered', 'section', 'teacher'), name='unique_distribution'),
        ),
        migrations.AddConstraint(
            model_name='courseoffered',
            constraint=models.UniqueConstraint(fields=('semester', 'batch', 'course'), name='unique_offering'),
        ),
    ]
