# Generated by Django 3.2.9 on 2022-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_batch_start_effect_date'),
        ('semester', '0004_auto_20220206_1220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursedistribution',
            name='unique_distribution',
        ),
        migrations.RemoveField(
            model_name='coursedistribution',
            name='section',
        ),
        migrations.AddField(
            model_name='coursedistribution',
            name='section',
            field=models.ManyToManyField(related_name='distributions', to='student.Section', verbose_name='Sections'),
        ),
    ]
