# Generated by Django 3.2.9 on 2022-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0006_mergedsectiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedistribution',
            name='section_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Section Title'),
        ),
    ]
