# Generated by Django 3.2.9 on 2022-02-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_batch_start_effect_date'),
        ('semester', '0007_coursedistribution_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedistribution',
            name='parent_dist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_dists', to='semester.coursedistribution', verbose_name='Parent Distribution'),
        ),
        migrations.RemoveField(
            model_name='coursedistribution',
            name='section',
        ),
        migrations.AddField(
            model_name='coursedistribution',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='student.section', verbose_name='Sections'),
            preserve_default=False,
        ),
    ]
