# Generated by Django 3.2.9 on 2022-02-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0008_auto_20220227_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedistribution',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='mergedsectiondetails',
            name='section',
        ),
    ]
