# Generated by Django 3.2.9 on 2022-02-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0009_auto_20220227_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedSectionDetails',
            new_name='DistributedSectionDetail',
        ),
    ]
