# Generated by Django 3.2.9 on 2022-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0010_rename_mergedsectiondetails_distributedsectiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributedsectiondetail',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_details', to='semester.coursedistribution', verbose_name='Distributed Course'),
        ),
    ]
