# Generated by Django 3.2.9 on 2022-02-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0011_alter_distributedsectiondetail_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributedsectiondetail',
            name='distribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_details', to='semester.coursedistribution', verbose_name='Distributed Course'),
        ),
    ]
