# Generated by Django 3.2.9 on 2022-03-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0012_alter_distributedsectiondetail_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
