# Generated by Django 3.2.9 on 2023-02-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0013_semester_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffered',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='courseoffered',
            name='unique_offering',
        ),
    ]
