# Generated by Django 3.2.9 on 2022-01-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20211201_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Teacher ID'),
        ),
    ]
