# Generated by Django 3.2.9 on 2022-01-11 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dean',
        ),
        migrations.CreateModel(
            name='FacultyDean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date_of_joining', models.DateField(default=datetime.datetime(2022, 1, 11, 6, 20, 58, 255329, tzinfo=utc), verbose_name='Date of Joining')),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deans', to='faculty.teacher', verbose_name='Dean')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deans', to='faculty.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Faculty Dean',
                'verbose_name_plural': 'Faculty Deans',
            },
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date_of_joining', models.DateField(default=datetime.datetime(2022, 1, 11, 6, 20, 58, 255329, tzinfo=utc), verbose_name='Date of Joining')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='faculty.department', verbose_name='Department')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='faculty.teacher', verbose_name='Head')),
            ],
            options={
                'verbose_name': 'Department Head',
                'verbose_name_plural': 'Department Heads',
            },
        ),
    ]
