# Generated by Django 3.2.9 on 2022-01-13 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20220111_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 6, 47, 40, 292274, tzinfo=utc), verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 13, 6, 47, 40, 291258, tzinfo=utc), verbose_name='Date of Joining'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(max_length=16, verbose_name='Course Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('credit', models.FloatField(verbose_name='Credit')),
                ('contact_hour', models.FloatField(verbose_name='Contact Hour')),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=8, verbose_name='Type')),
                ('pre_req', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='faculty.course', verbose_name='Pre Req')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='faculty.program', verbose_name='Program')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
