# Generated by Django 3.2.9 on 2022-01-16 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20220113_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 13, 53, 39, 87388, tzinfo=utc), verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 13, 53, 39, 86392, tzinfo=utc), verbose_name='Date of Joining'),
        ),
    ]
