# Generated by Django 3.2.9 on 2022-01-16 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_auto_20220116_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 14, 0, 53, 654516, tzinfo=utc), verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 14, 0, 53, 653520, tzinfo=utc), verbose_name='Date of Joining'),
        ),
    ]
