# Generated by Django 3.2.9 on 2022-01-28 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_auto_20220128_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 11, 28, 17, 627026, tzinfo=utc), verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 11, 28, 17, 626027, tzinfo=utc), verbose_name='Date of Joining'),
        ),
    ]
