# Generated by Django 3.2.9 on 2022-01-28 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('faculty', '0011_auto_20220128_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 11, 28, 22, 330042, tzinfo=utc),
                                   verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 11, 28, 22, 329046, tzinfo=utc),
                                   verbose_name='Date of Joining'),
        ),
    ]
