# Generated by Django 3.2.9 on 2022-01-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_auto_20220128_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthead',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='facultydean',
            name='date_of_joining',
        ),
    ]