# Generated by Django 3.2.9 on 2022-02-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_auto_20220221_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='total_credit',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='total_credit',
            field=models.FloatField(default=0.0, verbose_name='Total Credit'),
            preserve_default=False,
        ),
    ]
