# Generated by Django 3.2.9 on 2022-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_auto_20220221_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='end_effect_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Effect Date'),
        ),
    ]
