# Generated by Django 3.2.9 on 2022-02-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_alter_curriculum_end_effect_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
