# Generated by Django 3.2.9 on 2022-02-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_remove_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='faculty.program', verbose_name='Program'),
        ),
    ]
