# Generated by Django 3.2.9 on 2022-02-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
