# Generated by Django 3.2.9 on 2022-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_remove_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='facultydean',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='head',
            field=models.CharField(max_length=256, verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='dean',
            field=models.CharField(max_length=256, verbose_name='Faculty dean'),
        ),
    ]
