# Generated by Django 3.2.9 on 2023-02-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='faculty.course', verbose_name='Pre Req'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculty.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculty.department', verbose_name='Department'),
        ),
    ]
