# Generated by Django 3.2.9 on 2022-03-03 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0021_auto_20220303_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=8, verbose_name='Role')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bind_account', to='faculty.teacher', verbose_name='Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bind_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
