# Generated by Django 3.2.9 on 2022-01-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0005_auto_20220113_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('batch_code', models.CharField(max_length=128, verbose_name='Batch Code')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='faculty.program', verbose_name='Program')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=64, verbose_name='Section')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='student.batch', verbose_name='Batch')),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_sections', to='student.section', verbose_name='Parent Section')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
