# Generated by Django 3.2.9 on 2022-02-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_batch_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='start_effect_date',
        ),
    ]
